name: b2b-subscriptions-demo
version: '2.1'
services: 
  nocodb_b2b_subscriptions: 
    depends_on: 
      root_db_b2b_subscriptions_demo: 
        condition: service_healthy
    environment: 
      NC_DB: "pg://root_db_b2b_subscriptions_demo:5432?u=postgres&p=password&d=root_db"
      NC_DISABLE_TELE: "true"
    image: "nocodb/nocodb:latest"
    networks:
      - b2b_subscriptions_poc
    ports:
      - "8081:8080"
    restart: always
    volumes: 
      - "b2b_subscriptions_poc_nc_data:/usr/app/data"
  n8n_b2b_subscriptions_demo:
    environment:
      GENERIC_TIMEZONE: "Australia/Sydney"
      TZ: "Australia/Sydney"
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_RUNNERS_ENABLED: "true"
      N8N_SECURE_COOKIE: "false"
    image: "docker.n8n.io/n8nio/n8n"
    networks:
      - b2b_subscriptions_poc
    ports:
      - "5679:5678"
    restart: always
    volumes:
      - "b2b_subscriptions_n8n_data:/home/node/.n8n"
      - "./n8n-shared:/shared"
  root_db_b2b_subscriptions_demo: 
    environment: 
      POSTGRES_DB: root_db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    healthcheck: 
      interval: 10s
      retries: 10
      test: "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""
      timeout: 2s
    image: postgres:16.6
    networks:
      - b2b_subscriptions_poc
    restart: always
    volumes: 
      - "b2b_subscriptions_poc_db_data:/var/lib/postgresql/data"
  
volumes: 
  b2b_subscriptions_poc_db_data:
  b2b_subscriptions_poc_nc_data:
  b2b_subscriptions_n8n_data:
networks:
  b2b_subscriptions_poc:

